import {dataInterface} from './types'
const Menu:dataInterface[] = [
    {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'redmi',
        price: 15.99,
        img: './images/redmi9.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
      {
        id: 2,
        title: 'diner double',
        category: 'redmi',
        price: 13.99,
        img: './images/redmi note 9.jpeg',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
      },
      {
        id: 3,
        title: 'godzilla milkshake',
        category: 'realme',
        price: 6.99,
        img: './images/realme 5s.jpeg',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
      },
      {
    id: 4,
        title: 'Dinner special',
        category: 'realme',
        price: 6.99,
        img: './images/realme X50.jpeg',
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`
      },
      {
        id: 5,
        title: 'country delight',
        category: 'realme',
        price: 20.99,
        img: './images/realme 3.jpeg',
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
      },
      {
        id: 6,
        title: 'egg attack',
        category: 'redmi',
        price: 22.99,
        img: './images/redmi note 9 pro.jpeg',
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
      },
      {
        id: 7,
        title: 'oreo dream',
        category: 'realme',
        price: 18.99,
        img: './images/realme 5s.jpeg',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
      },
      {
        id: 8,
        title: 'strawberry ice cream',
        category: 'redmi',
        price: 18.99,
        img: './images/redmi K20.jpeg',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
      },
      {
        id: 9,
        title: 'Blue Moon ice cream',
        category: 'realme',
        price: 18.99,
        img: './images/realme X50.jpeg',
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
      },
      {
        id: 10,
        title: 'bacon overflow',
        category: 'redmi',
        price: 8.99,
        img: './images/redmi note 8.jpeg',
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
      },
      {
        id: 10,
        title: 'american classic',
        category: 'oppo',
        price: 12.99,
        img: './images/oppo A31.jpeg',
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
      },
      {
        id: 11,
        title: 'quarantine buddy',
        category: 'oppo',
        price: 16.99,
        img: './images/oppo A54.jpeg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      },
      {
        id: 12,
        title: "pav bhaji",
        category: "samsung",
        price: 49.99,
        img: './images/Samsung galaxy M51.jpeg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      },
      {
        id: 13,
        title: "vada pav",
        category: "samsung",
        price: 10.99,
        img: './images/Samsung galaxy S21.jpeg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      },
      {
        id: 14,
        title: "Bruschetta",
        category: 'Vivo',
        price: 306.99,
        img: './images/Vivo Y20G.jpeg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      },
      {
        id: 15,
        title: "Samosa",
        category: "Oneplus",
        price: 49.99,
        img: './images/Oneplus Nord CE.jpeg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      },
      {
        id: 16,
        title: "Mahathali",
        category: "Oneplus",
        price: 99.99,
        img: './images/Oneplus 9R.jpeg',
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      },
       {
        id: 17,
        title: 'bagel',
        category: 'Vivo',
        price: 15.99,
        img: './images/Vivo Y12s.jpeg',
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      },
    ];
    export {Menu};